### ISSUE TITLE
castling is broken

### ISSUE THREAD

**Issue by vindognz** [kit-solent/chess#1]
if you try castle it kinda does this:

![image](https://github.com/user-attachments/assets/02dc19ba-fd60-491e-b180-ea363febc3d6)

**Comment by vindognz** [comment]
*moves the king and leaves the rook behind*

**Comment by kit-solent** [comment]
You have to get the other player to pass so you can make both moves in a row. The idea behind this app is to provide a board to play on not to enforce every move (mostly because that was to hard).
