### ISSUE TITLE
linux support

### ISSUE THREAD

**Issue by vindognz** [kit-solent/chess#2]

**Comment by vindognz** [comment]
add linux support like this:

ip_address = IP.get_local_addresses()[0]

**Comment by vindognz** [comment]
idk if work on mac. but screw mac anyways/

**Comment by kit-solent** [comment]
Put the bash to get private ip here and i'll do it.

**Comment by vindognz** [comment]
ip addr | grep 'inet ' | grep 'wlp1s0' | awk '{print $2}' | cut -d'/' -f1

**Comment by vindognz** [comment]
var interfaceTIng = exectureorwahwtever("ip addr | grep 'state UP' | awk '{print $2}' | sed 's/://' | grep '^wl'")
executeting("ip addr | grep 'inet ' | grep 'wlp1s0' | awk '{print $2}' | cut -d'/' -f1")

**Comment by kit-solent** [comment]
pull request plz. Linux is not worth my time implimenting this myself but I'm happy to use your pull request if you make one.

**Comment by vindognz** [comment]
func get_wifi_interface() -> String:
	# Command to list network interfaces
	var cmd := "ip addr | grep 'state UP' | awk '{print $2}' | sed 's/://' | grep '^wl'"
	var proc = Process.new()
	var interface_name = ""

	if proc.execute("/bin/bash", ["-c", cmd], true) == OK:
		interface_name = proc.get_stderr().strip_edges() if proc.get_stderr() != "" else proc.get_stdout().strip_edges()

	return interface_name


func get_ip_for_interface() -> String:
	var interface_name = get_wifi_interface()
	if interface_name == "":
		print("No Wi-Fi interface found.")
		return ""
	
	var cmd := "ip addr | grep 'inet ' | grep '" + interface_name + "' | awk '{print $2}' | cut -d'/' -f1"
	var proc = Process.new()
	var result := ""
	
	if proc.execute("/bin/bash", ["-c", cmd], true) == OK:
		result = proc.get_stderr().strip_edges() if proc.get_stderr() != "" else proc.get_stdout().strip_edges()
	
	return result

**Comment by vindognz** [comment]
```
func get_wifi_interface() -> String:
	# Command to list network interfaces
	var cmd := "ip addr | grep 'state UP' | awk '{print $2}' | sed 's/://' | grep '^wl'"
	var proc = Process.new()
	var interface_name = ""

	if proc.execute("/bin/bash", ["-c", cmd], true) == OK:
		interface_name = proc.get_stderr().strip_edges() if proc.get_stderr() != "" else proc.get_stdout().strip_edges()

	return interface_name


func get_ip_for_interface() -> String:
	var interface_name = get_wifi_interface()
	if interface_name == "":
		print("No Wi-Fi interface found.")
		return ""
	
	var cmd := "ip addr | grep 'inet ' | grep '" + interface_name + "' | awk '{print $2}' | cut -d'/' -f1"
	var proc = Process.new()
	var result := ""
	
	if proc.execute("/bin/bash", ["-c", cmd], true) == OK:
		result = proc.get_stderr().strip_edges() if proc.get_stderr() != "" else proc.get_stdout().strip_edges()
	
	return result

```

**Comment by kit-solent** [comment]
If you make a pull request then I'll merge it after I've submitted the standard. I can't do so beforehand because all the code has to be my own.

**Comment by kit-solent** [comment]
@vindognz you making a pull request? I know I'm not. I'm going to close this issue though because having an open issue on my final submision looks bad.
