### ISSUE TITLE
if the host quits the game, error

### ISSUE THREAD

**Issue by vindognz** [kit-solent/chess#4]
piece moved
ERROR:ree_exited', callable: ''.onexistent connection from 'Core:<Node#26524779711>'. Signal: 't
   at: (core/object/object.cpp:1462)
ERROR:: 'tree_exited', callable: ''.istent connection from 'board:<Control#46321894903>'. Signal
   at: (core/object/object.cpp:1462)
^C01e8:fixme:console:default_ctrl_handler Terminating process 180 on event 0

**Comment by kit-solent** [comment]
I fixed it. Wait for the next commit.
